apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: voteapp-dev
  labels:
    app: example-voting-app
    name: postgres-service
spec:
  type: ClusterIP
  ports:
  - name: "postgres-service"
    port: 5432
    targetPort: 5432
  selector:
    app: example-voting-app
    name: postgres-pod