apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voteapp-dev
  labels:
    app: example-voting-app
    name: redis-service
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379
  selector:
    app: example-voting-app
    name: redis-pod
  

