apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voteapp-dev
  labels:
    app: example-voting-app
    name: result-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: example-voting-app
    name: result-pod
