apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voteapp-dev
  labels:
    app: example-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-voting-app
      name: vote-pod
  template:
    metadata:
      name: vote-pod
      labels:
        app: example-voting-app
        name: vote-pod
    spec:
      containers:
      - image: tomekirov/examplevotingapp_vote:1.0
        name: vote
        imagePullPolicy: Always
        readinessProbe:
            httpGet:
              port: 80
              path: /
        livenessProbe:
            httpGet:
              port: 80
              path: /
